<a href="https://colab.research.google.com/github/MohammedZaid-AI/Smart-Coffee-Recommender/blob/master/train.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import joblib

In [34]:
data=pd.read_csv("/content/Coffe_sales.csv")

In [35]:
data.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000

In [36]:
data['day_of_the_week']=pd.to_datetime(data['Date']).dt.dayofweek

In [37]:
def get_time_of_day(hour):
  if 5>= hour >=12:
    return "Morning"
  elif 13>= hour >=16:
    return "Afternoon"
  else:
    return "Evening"

In [38]:
data['hour']=pd.to_datetime(data['Time'], format='mixed').dt.hour
data['time_of_day']=data['hour'].apply(get_time_of_day)

In [39]:
data.head()

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort,Date,Time,day_of_the_week,hour,time_of_day
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3,2024-03-01,10:15:50.520000,4,10,Evening
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:19:22.539000,4,12,Evening
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3,2024-03-01,12:20:18.089000,4,12,Evening
3,13,card,28.9,Americano,Afternoon,Fri,Mar,5,3,2024-03-01,13:46:33.006000,4,13,Evening
4,13,card,38.7,Latte,Afternoon,Fri,Mar,5,3,2024-03-01,13:48:14.626000,4,13,Evening

In [40]:
x=data[['day_of_the_week','time_of_day']]
y=data['coffee_name']

In [41]:
le_time = LabelEncoder()
le_day = LabelEncoder()
le_coffee = LabelEncoder()
x.loc[:,'day_of_the_week']=le_day.fit_transform(x['day_of_the_week'])
x.loc[:,'time_of_day']=le_time.fit_transform(x['time_of_day'])
y=le_coffee.fit_transform(y)

/tmp/ipykernel_15756/1592106926.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[4 4 4 ... 6 6 6]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  x.loc[:,'day_of_the_week']=le_day.fit_transform(x['day_of_the_week'])

In [42]:
model=RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x,y)

RandomForestClassifier(random_state=42)

In [43]:
def predict_coffee(day_of_the_week, time_of_day):
  day_of_the_week_encoded=le.transform([day_of_the_week])[0]
  time_of_day_encoded=le.transform([time_of_day])[0]

  predict=model.predict([[day_of_the_week_encoded, time_of_day_encoded]])
  return le.inverse_transform(predict)[0]

In [44]:
joblib.dump(model, "coffee_model.pkl")

['coffee_model.pkl']

In [45]:
joblib.dump(le_day, "le_day.pkl")

['le_day.pkl']

In [46]:
joblib.dump(le_time, "le_time.pkl")

['le_time.pkl']

In [47]:
joblib.dump(le_coffee, "le_coffee.pkl")

['le_coffee.pkl']